version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: confradar-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-confradar}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-confradar}
      POSTGRES_DB: ${POSTGRES_DB:-confradar}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U confradar"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-proxy
    ports:
      - "4000:4000"
    environment:
      # Prefer the service account key if present, else fall back to OPENAI_API_KEY
      OPENAI_API_KEY: ${CONFRADAR_SA_OPENAI:-${OPENAI_API_KEY:-}}
      # Optional logging level: debug|info|warning|error
      LITELLM_LOG: info
    command: ["uvicorn", "litellm.proxy:app", "--host", "0.0.0.0", "--port", "4000"]
    restart: unless-stopped

  dagster-daemon:
    build:
      context: .
      dockerfile: Dockerfile.dagster
    container_name: dagster-daemon
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://confradar:confradar@postgres:5432/confradar}
      CONFRADAR_SA_OPENAI: ${CONFRADAR_SA_OPENAI:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    volumes:
      - ./packages/confradar:/opt/dagster/app
      - dagster_data:/opt/dagster/data
      - dagster_home:/opt/dagster/dagster_home
    command: ["uv", "run", "dagster-daemon", "run"]
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      litellm:
        condition: service_started

  dagster-webserver:
    build:
      context: .
      dockerfile: Dockerfile.dagster
    container_name: dagster-webserver
    ports:
      - "3000:3000"
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://confradar:confradar@postgres:5432/confradar}
      CONFRADAR_SA_OPENAI: ${CONFRADAR_SA_OPENAI:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    volumes:
      - ./packages/confradar:/opt/dagster/app
      - dagster_data:/opt/dagster/data
      - dagster_home:/opt/dagster/dagster_home
    command: ["uv", "run", "dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      dagster-daemon:
        condition: service_started
      litellm:
        condition: service_started

volumes:
  postgres_data:
  dagster_data:
  dagster_home:
