[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "confradar"
version = "0.1.0"
description = "AI-powered agent to track academic conference deadlines"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [ { name = "orgroman" } ]
keywords = ["conferences", "deadlines", "scraping", "LLM", "NLP"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
  "beautifulsoup4>=4.12",
  "dateparser>=1.2",
  "httpx>=0.27",
  "pydantic>=2.6",
  "pydantic-settings>=2.3",
  "litellm>=1.43.0",
  "SQLAlchemy>=2.0",
  "psycopg[binary]>=3.1",
  "scrapy>=2.11",
  "playwright>=1.40",
  "dagster>=1.8",
  "dagster-webserver>=1.8",
  "fastapi>=0.104",
  "uvicorn[standard]>=0.24",
]

[project.optional-dependencies]
dev = [
  "black>=24.3",
  "ruff>=0.6",
  "mypy>=1.10",
  "pytest>=8.2",
  "pytest-cov>=5.0",
  "pre-commit>=3.7",
  "alembic>=1.13",
]

[project.scripts]
# The CLI entrypoint lives in the library for reuse; the app will publish this script in releases
# Keeping it here ensures local runs work even if the app isn't installed separately
confradar = "confradar.cli:main"

[tool.black]
line-length = 100
target-version = ["py310", "py311"]

[tool.ruff]
line-length = 100
target-version = "py310"
lint.select = ["E", "F", "I", "UP", "B"]
lint.ignore = ["E203", "E266", "E501"]

[tool.pytest.ini_options]
addopts = "-q"
# When running tests from the package directory
testpaths = ["tests"]
markers = [
  "integration: marks tests that make real network calls (deselect with '-m \"not integration\"')"
]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "bandit>=1.8.6",
    "detect-secrets>=1.5.0",
    "safety>=3.6.2",
]
