name: Bug report
description: Report a bug or regression
title: "bug: <short summary>"
labels: ["type:bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out a bug report!"
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the bug is.
      placeholder: e.g., Change detection fails when date format includes AoE
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide the steps and any inputs/URLs to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant logs or add screenshots if helpful.
      render: shell
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - area:retrieval
        - area:extraction
        - area:clustering
        - area:kb
        - area:serving
        - area:infra
  - type: input
    id: version
    attributes:
      label: Version/commit
      description: Tag, branch, or commit SHA.
