"""init schema

Revision ID: 6734aa7c5266
Revises: 
Create Date: 2025-10-25 19:27:53.775393+00:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6734aa7c5266'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('homepage', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_conference_key')
    )
    op.create_index('ix_conference_name', 'conferences', ['name'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conference_id', 'url', name='uq_source_conf_url')
    )
    op.create_index('ix_source_url', 'sources', ['url'], unique=False)
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conference_id', 'kind', 'due_date', name='uq_deadline_unique')
    )
    op.create_index('ix_deadline_due_date', 'deadlines', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deadline_due_date', table_name='deadlines')
    op.drop_table('deadlines')
    op.drop_index('ix_source_url', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_conference_name', table_name='conferences')
    op.drop_table('conferences')
    # ### end Alembic commands ###
