name: CI

on:
  push:
    branches: [ main, "feat/**", "fix/**" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests (uv)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        shell: bash
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify uv
        run: uv --version
        shell: bash

      - name: Sync workspace deps (dev extras)
        shell: bash
        run: uv sync --extra dev

      - name: Run tests
        shell: bash
        run: |
          cd packages/confradar
          # Skip integration tests due to Scrapy reactor issue (see #83)
          # Skip database tests until PostgreSQL service added (see #84)
          uv run pytest -q --ignore=tests/test_integration_scrapers.py --ignore=tests/test_database_pipeline.py
