name: CI

on:
  push:
    branches: [ main, "feat/**", "fix/**" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests (uv)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install uv (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          iwr -useb https://astral.sh/uv/install.ps1 | iex
          echo "$Env:USERPROFILE\.local\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify uv
        run: uv --version
        shell: bash

      - name: Sync workspace deps (dev extras)
        shell: bash
        run: uv sync --extra dev

      - name: Run tests
        shell: bash
        run: |
          cd packages/confradar
          uv run pytest -q
