name: Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: confradar
          POSTGRES_PASSWORD: confradar
          POSTGRES_DB: confradar_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        shell: bash
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify uv
        run: uv --version

      - name: Sync workspace deps (dev extras)
        run: uv sync --extra dev

      - name: Run tests with coverage
        env:
          DATABASE_URL: postgresql+psycopg://confradar:confradar@localhost:5432/confradar_test
        run: |
          cd packages/confradar
          # Skip integration tests due to Scrapy reactor issue (see #83)
          # Database tests now enabled with PostgreSQL service (#84 resolved)
          uv run pytest \
            --cov=src/confradar \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-report=html \
            --cov-fail-under=45 \
            --ignore=tests/test_integration_scrapers.py

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: packages/confradar/htmlcov/
