name: Frontend CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'web/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'web/**'
      - '.github/workflows/frontend.yml'

defaults:
  run:
    working-directory: web

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Avoid cache errors when no lockfile is present; caching can be re-enabled once lockfile is committed

      - name: Install dependencies (ci if lockfile, else install)
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "package-lock.json not found, using npm install"
            npm install
          fi

      # Type checking is performed during `next build`; running tsc separately can
      # diverge from Next's resolver behavior. We rely on build-time checks.

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
