name: Security Scan

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  security:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        shell: bash
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify uv
        run: uv --version

      - name: Sync workspace deps (dev extras)
        run: uv sync --extra dev

      - name: Run bandit (security linter)
        run: |
          cd packages/confradar
          uv run bandit -r src -ll -f txt || true

      - name: Run safety (dependency vulnerability check)
        continue-on-error: true  # Don't fail on vulnerabilities yet, just report
        run: |
          cd packages/confradar
          uv pip list --format json | uv run safety check --stdin

      - name: Check for secrets with detect-secrets
        run: |
          cd packages/confradar
          uv run detect-secrets scan --baseline .secrets.baseline || echo "No baseline, skipping"
