name: Sync Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/wiki/**'
      - '.github/workflows/sync-wiki.yml'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync docs/wiki to wiki
        run: |
          rsync -av --delete docs/wiki/ wiki/

      - name: Commit and push changes to wiki
        working-directory: wiki
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Sync wiki from docs/wiki @ $GITHUB_SHA"
            git push
          else
            echo "No changes to commit"
          fi
